### ISSUE TITLE
Lot of missing streets

### ISSUE THREAD

**Issue by cskau** [veltman/clmystery#1]
On my first play-through I seem to have hit a dead end.

From the clues I managed to derive a list of names of people I'd like to talk to, as I figure was the intention. But unfortunately it seems the very first person - and as it turn out, quite a lot of other people - are utter ghosts; the streets they live on are non-existing.

Given the sheer scale of this I'm assuming this is not some intricate part of the yet-to-uncovered plot.

I've derived a quick list of the 2541 street that are listed as someone's address in the people file, but does not exist in the streets folder, but given it's size I'll post this separately below.

**Comment by sukima** [comment]
Possible spoiler: I did use the fact that there were missing streets to narrow down my search. So the lack of data was helpful.

**Comment by veltman** [comment]
I've gone back and forth on this. It could be confusing but as long as you deal with the clues in combination it shouldn't lead you astray, and having some dead ends in the data is a nice true-to-life wrinkle, so I'm going to leave this alone for now. Doesn't seem to have tripped up many people.
