### ISSUE TITLE
Detective Notepad++

### ISSUE THREAD

**Issue by RStrydom** [veltman/clmystery#12]
I found that I wanted to store the output of my commands in order to track my progress.
Now this can be done easily by creating a new file and adding your command output to the file. The thing is it felt "contaminating" to do this inside the git repo as I might possible want to make changes for a pull request.

So I think it would be quite cool if you have a dedicated file to add your "notes" into and that will be ignored in a .gitignore file.

This will also teach people not familiar with the command line the ">>" append, which I saw is briefly mentioned in the cheatsheet.

Was great fun and can't wait to see how this game evolves.

**Comment by veltman** [comment]
Hmm, interesting idea. Will have to think about how it would be implemented in a way that's beginner-friendly though.
