### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by ToostInc** [veltman/clmystery#13]
I realise this may be a weird question, but I maintain an AUR package for Arch Linux for this project, and it'd greatly help if I knew under what terms it can be redistributed, or if it can be redistributed at all.

So I wondered if you'd given it any thought? GPL? Creative Commons? I'd also greatly appreciate it if you could include a LICENSE file in the repository I can optionally link to.

Thanks anyway!

**Comment by veltman** [comment]
Added a LICENSE.md with 66d6a88a
