### ISSUE TITLE
[SPOILERS] Command for checking solution doesn't work

### ISSUE THREAD

**Issue by Futile** [veltman/clmystery#17]
Hi, on my system the command to check a solution does not work.

This is the command I'm executing (copied from the `solution` file):

```
[felix@sun clmystery]$ echo "[the answer]" | $(command -v md5 || command -v md5sum) | grep -qf /dev/stdin solution && echo CORRECT\! GREAT WORK, GUMSHOE. || echo SORRY, TRY AGAIN.
```

and the output is:

```
SORRY, TRY AGAIN.
```

while the command for revealing the solution outputs exactly the name I entered. This happens in both zsh and bash.

**Comment by veltman** [comment]
1) What OS are you using?

2) What happens if you just run:

    echo "[the answer]" | $(command -v md5 || command -v md5sum)

3) What happens if you just run:

    grep -q "32cacbec4b918e2fd130fd68cf818ae5" solution && echo $?

**Comment by Futile** [comment]
1) Archlinux
2)
```
felix@sun ~/gits/clmystery (git)-[master] % echo "Jeremy Bowers" | $(command -v md5 || command -v md5sum)
32CACBEC4B918E2FD130FD68CF818AE5  -
```

3)
```
felix@sun ~/gits/clmystery (git)-[master] % grep -q "32cacbec4b918e2fd130fd68cf818ae5" solution && echo $?
0
```

The md5sum from 2) is uppercase, and thus isn't matched by grep. Using `grep -qif` instead of `grep -qf` makes it work. Thanks for the quick answer! :)

**Comment by veltman** [comment]
Ohhh interesting.  I'll add the `-i`, thanks!

**Comment by veltman** [comment]
Also strange that `md5sum` is all uppercase for you, I tested this with `m5sum` on Ubuntu and it was lowercase!

**Comment by Futile** [comment]
> Also strange that md5sum is all uppercase for you, I tested this with m5sum on Ubuntu and it was lowercase!

Mhhm, my `md5sum` was also lowercase, it was the `md5` that produced uppercase output (see my previous edit). But anyways, same thing :)
