### ISSUE TITLE
Solution Error

### ISSUE THREAD

**Issue by rhymeswithfloral** [veltman/clmystery#18]
Command for checking solution is resulting in an error. 
`grep: /dev/stdin: No such file or directory`
`SORRY, TRY AGAIN.`
This is a picture of error in the Git Bash terminal, despite the correct answer being inputted into the command. [cmlsolutionerror.jpg](https://cloud.githubusercontent.com/assets/16247185/12734777/ae0f9262-c910-11e5-8f25-031e6b07ee69.jpg) **spoiler alert**

**Comment by veltman** [comment]
What operating system are you using?

**Comment by veltman** [comment]
I believe this is a Windows problem, I've clarified the instructions with 6dd30f8
