### ISSUE TITLE
Conclusion

### ISSUE THREAD

**Issue by kumavis** [veltman/clmystery#2]
This is awesome!
Great idea, and nice execution!

I felt like the conclusion was a little anti-climactic (unless I missed something). After figuring out the murderer's name it was sort of... "well, am i done now?" 
Would have enjoyed more of a catch at the end of the chase.

But most importantly I learned some new commands and flags, so job well done :grinning: 

Are you planning on continuing this project?

**Comment by talassio** [comment]
This is great! @veltman, The idea is really enjoyable! but needs a longer story, keep the idea alive! ;)
